### ISSUE TITLE
Добавить в настройку автоматический выбор правильного ответа и отправку

### ISSUE THREAD

**Issue by MelnikovIG** [nhusnullin/LectoraExtension#1]
Добавить в настройку автоматический выбор правильного ответа и отправку

**Comment by serber** [comment]
Я добавил подсветку и выбор правильного ответа, но нет прав на push.
@nhusnullin, если дашь доступ, сделаю PR.

**Comment by MelnikovIG** [comment]
@serber ты можешь создать пр через свою ветку в твоём форке репозитория

**Comment by serber** [comment]
@MelnikovIG
PR https://github.com/nhusnullin/LectoraExtension/pull/2

**Comment by nhusnullin** [comment]
вошло в релиз 1.2
